//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeighRMonitoring.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int BatchId { get; set; }
        public string BatchCode { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public bool isCurrent { get; set; }
        public string ClientId { get; set; }
        public bool persistedServer { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
