//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeighRMonitoring.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public int Id { get; set; }
        public Nullable<int> PlantId { get; set; }
        public string MachineName { get; set; }
        public string DeviceId { get; set; }
        public string iotHubDeviceKey { get; set; }
        public string SerialNumber { get; set; }
        public string GPSCoordinates { get; set; }
        public string userId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
