//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeighRMonitoring.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public string ReportName { get; set; }
        public string ReportDescription { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ReportURL { get; set; }
    }
}
