//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeighRMonitoring.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public long TransactionLogId { get; set; }
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public decimal ActualWeight { get; set; }
        public string BatchCode { get; set; }
        public string OrderNumber { get; set; }
        public decimal ProductDensity { get; set; }
        public int ShiftId { get; set; }
        public decimal TargetWeight { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Units { get; set; }
        public decimal WeightDifference { get; set; }
        public int WeightStatus { get; set; }
        public string WeightType { get; set; }
        public bool persistedServer { get; set; }
        public string DeviceId { get; set; }
        public string ClientId { get; set; }
        public string PlantId { get; set; }
        public string MachineName { get; set; }
        public Nullable<bool> Uploaded { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> ExpectedFillTime { get; set; }
        public Nullable<decimal> ActualFillTime { get; set; }
        public Nullable<decimal> PercDiffFillTime { get; set; }
        public string BaseUnitOfMeasure { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> LowerLimit { get; set; }
        public Nullable<decimal> UpperLimit { get; set; }
        public string ProductName { get; set; }
    }
}
